server.port=8091
spring.application.name=payment-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Resilience4j Circuit Breaker config
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3

# Actuator
management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always
